### ISSUE TITLE
Not working with @web/dev-server

### ISSUE THREAD

**Issue by rajasegar** [esm-bundle/react#90] opened 2020-11-18 12:22 UTC
This package is not working with [@web/dev-server](https://modern-web.dev/docs/dev-server/overview/) . The browser hangs when try to load the app. 
Example reproduction is [here](https://github.com/rajasegar/react-htm-esm-build)
However it is working find with [snowpackjs/react](https://github.com/snowpackjs/react)

**Comment by joeldenning** [comment] 2020-11-20 16:56
This is caused by using the development version of react-dom, but the production version of react. The reason that `@web/dev-server` is using those versions is because the `main` field in the package.json of `@esm-bundle/react` points to the production version, but the equivalent in `@esm-bundle/react-dom` points to the development version. I'll change the main field and publish a fix.

**Comment by joeldenning** [comment] 2020-11-20 17:00
Fixed in 5ff7a17b3bdb1d674f0369fe9baeef869fcf6c3a and released in https://github.com/esm-bundle/react/releases/tag/v17.0.1-fix.0

**Closed by joeldenning** 2020-11-20 17:00 UTC
